name: Good Morning

on:
  schedule:
    # 毎日午前7時に実行されるスケジュール (UTC時間なので、日本時間では+9時間)
    - cron: '8 * * * *'

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # 使用するPythonのバージョンを指定

      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}  # requirements.txtがある場合
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy

      - name: Run main.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET_TOKEN: ${{ secrets.ACCESS_SECRET_TOKEN }}
        run: |
          TODAY=$(date -d '9 hours' '+%m月%d日')
          echo "${TODAY}の朝だよ！学校きてね！"
          python main.py "${TODAY}の朝だよ！学校きてね！"
